.gitignore
README.md
dizquetv-nvidia.xml
dizquetv.xml
index.js
src/api.js
src/channel-cache.js
src/ffmpeg-info.js
src/ffmpeg.js
src/program-player.js
src/video.js
src/xmltv.js
web/controllers/version.js
web/directives/channel-config.js
web/directives/plex-library.js
web/public/index.html
web/public/templates/channel-config.html
web/public/templates/ffmpeg-settings.html
web/public/templates/plex-library.html
web/public/views/version.html
web/services/plex.js

Changes for 0.0.62

---

.gitignore
README.md
dizquetv-nvidia.xml
dizquetv.xml
index.js
src/api.js
src/channel-cache.js
src/constants.js
src/ffmpeg-info.js
src/ffmpeg.js
src/program-player.js
src/video.js
src/xmltv.js
web/controllers/version.js
web/directives/channel-config.js
web/directives/plex-library.js
web/public/index.html
web/public/templates/channel-config.html
web/public/templates/ffmpeg-settings.html
web/public/templates/plex-library.html
web/public/views/version.html
web/services/plex.js

Release 0.0.62

---

src/api.js

tvg-chno in M3U

---

web/directives/ffmpeg-settings.js

480x270 resolution in ffmpeg

---

index.js
src/channel-cache.js
src/dao/channel-db.js
src/helperFuncs.js
src/plex-player.js
src/program-player.js
src/video.js
web/app.js
web/directives/channel-config.js
web/directives/channel-redirect.js
web/public/templates/channel-config.html
web/public/templates/channel-redirect.html
web/public/templates/plex-server-edit.html

This will add channel redirects feature. But the tv guide doesn't support it yet. (tv guide treats it the same as flex)
...

20200824 dev

---

src/api.js
src/ffmpeg.js
src/helperFuncs.js
src/video.js
src/xmltv.js
web/directives/channel-config.js
web/public/templates/channel-config.html
web/public/templates/xmltv-settings.html

* Reruns
* Async xmltv delivery.
* If for some reason a channel's start time is ahead of the present, dizquetv will just play/schedule Flex time instead of erroring out/generating an empty xmltv file.
* Remove minimum rates from ffmpeg transcoding. It's not recommended to constraint the bitrate that much and maximum seems to be useful one.
* Log that will tell you when ffmpeg is transcoding and when it is only copying.
...

20200826 dev

---

README.md
index.js
src/api.js
src/channel-cache.js
src/constants.js
src/dao/channel-db.js
src/ffmpeg.js
src/helperFuncs.js
src/plex-player.js
src/program-player.js
src/video.js
src/xmltv.js
web/app.js
web/directives/channel-config.js
web/directives/channel-redirect.js
web/directives/remove-shows.js
web/public/templates/channel-config.html
web/public/templates/channel-redirect.html
web/public/templates/plex-server-edit.html
web/public/templates/remove-shows.html
web/public/templates/xmltv-settings.html

20200826 main

---

index.js
src/api.js
src/constants.js
src/plex.js
src/tv-guide-service.js
src/xmltv.js
web/app.js
web/controllers/guide.js
web/public/index.html
web/public/style.css
web/public/templates/channel-config.html
web/public/templates/ffmpeg-settings.html
web/public/views/guide.html
web/services/dizquetv.js

20200904 guide

---

index.js
src/api.js
src/ffmpeg.js
src/hdhr.js
src/plexTranscoder.js
src/tv-guide-service.js
src/video.js
web/public/style.css
web/public/templates/channel-config.html
web/public/views/channels.html
web/public/views/guide.html

- TV Guide > Fix bug with missing channel redirects.
- If there are errors when generating the guide, it will retry until it works.
- "Smart" resize instead of relying on ffmpeg for the logic. This fixes the bug with anamorphic video getting messed up aspect ratios.
- Normalize resolution will always normalize anamorphic videos, even if they have the same dimensions.
- When transcoding and normalize resolution being off, padding will not be added. But there's a special case for odd dimensions, where it needs to add 1 pixel.
- Changed scaling algorithm to 'billinear_fast'. It has 'fast' in the name, so hopefully it's faster?
- TV Guide has a play button. And you can play channels from within the TV guide. in theory.
- Stealth mode for channels.
- Fixes for new setups.
...

20200905 dev

---

README.md
src/constants.js

Prepare 0.0.67 development

---

index.js
src/tv-guide-service.js

20200905 67

---

README.md
src/constants.js

Prepare 0.0.68 development

---

package.json
web/app.js
web/directives/channel-config.js
web/public/templates/channel-config.html

Virtual Scroll for channel editor.
Consquences:
* There should be less lag in the channel editor, specially with large channels.
* Since virtual scroll requires all elements to have the same height, the heights of programs is no longer proportional to their duration.
* Annoying Horizontal bar is gone, now you can just scroll the programs list up or down naturally.
...

Virtual Scroll for channel editor. Big thanks to @TimeBomb for the help.

---

README.md
src/tv-guide-service.js

20200907 night

---

index.js
src/tv-guide-service.js
web/directives/channel-config.js
web/public/index.html
web/public/style.css
web/public/templates/channel-config.html
web/public/templates/offline-config.html
web/public/templates/plex-library.html
web/public/templates/plex-server-edit.html
web/public/templates/plex-settings.html
web/public/templates/remove-shows.html
web/public/views/channels.html

20200909 dev

---

src/ffmpeg.js
src/plexTranscoder.js
web/directives/channel-config.js
web/directives/plex-settings.js
web/public/templates/channel-config.html
web/public/templates/plex-settings.html

- Do not allow to enable subtitles when direct play is being forced.
- Fix error stream not working. Streams should be more resilient now.
- Improved logs for when and how ffmpeg processes end.
- New Channel Tool: Save/Recover TV show positions.
- Horizontal indicator for program duration in channel editor.
...

20200910 dev

---

README.md
src/constants.js

Prepare 0.0.69 development

---

README.md
src/constants.js

Prepare 0.0.70 development

---

src/tv-guide-service.js
src/video.js
web/controllers/guide.js
web/directives/offline-config.js
web/public/templates/offline-config.html

20200917 dev

---

src/tv-guide-service.js
src/video.js
web/controllers/guide.js
web/directives/offline-config.js
web/public/templates/offline-config.html

This is to include the bug fixes in 1.0.1 in the 1.1.x branch.
...

20200918 dev

---

README.md
src/constants.js
web/public/templates/channel-config.html

- Prepare 1.0.2 development
- Fix Tool Help
...

20200921 dev

---

web/directives/channel-config.js
web/directives/program-config.js
web/public/templates/program-config.html

Fix #132 Save Program not working at all.

---

src/plexTranscoder.js

Fix anamorphic video (again), when audio is transcoded by plex but video is direct played. #127

Fix anamorphic video (again), when audio is transcoded by plex but video is direct played. #127

---

web/directives/channel-config.js
web/public/style.css
web/public/templates/channel-config.html
web/public/templates/filler-config.html
web/public/views/channels.html
web/public/views/filler.html

Channel Editor Rework

---

web/public/style.css
web/public/templates/channel-config.html

Makes Tools buttons/inputs more consistent with each other and makes border more noticeable to help add some contrast to all the amber color in the buttons.
Before:
After:

Polish styles for Tools buttons

---

web/directives/channel-config.js
web/public/style.css
web/public/templates/channel-config.html

Channel tools can be changed. The editor will remember tools being open and their position. Some visual tweaks
...

Channel tools can be changed. The editor will remember tools being open and their position. Some visual tweaks

---

src/database-migration.js
src/ffmpeg.js
src/helperFuncs.js
src/plex-player.js
src/program-player.js
web/directives/channel-config.js
web/directives/ffmpeg-settings.js
web/public/style.css
web/public/templates/channel-config.html
web/public/templates/ffmpeg-settings.html

FFMPEG channel editor tab. Channel watermark options.

FFMPEG channel editor tab. Channel watermark options.

---

src/helperFuncs.js

Fixerror when channels don't have the watermark enabled.

---

src/ffmpeg.js
src/video.js
web/app.js
web/directives/channel-config.js
web/directives/ffmpeg-settings.js
web/public/templates/channel-config.html
web/services/resolution-options.js

Channel resolution and bitrate settings.

Channel resolution and bitrate settings.

---

src/api.js
src/ffmpeg.js
src/services/time-slots-service.js
src/tv-guide-service.js
web/app.js
web/directives/channel-config.js
web/directives/time-slots-schedule-editor.js
web/public/templates/channel-config.html
web/public/templates/time-slots-schedule-editor.html
web/services/dizquetv.js

* fix bufSize crash
* Time Slots
* [ X I am submitting to the correct base branch

20201010 dev

---

README.md
src/constants.js
web/public/style.css
web/public/templates/filler-config.html

Fix #164 : Filler List getting compressed in Webkit (Safari)

 Fix #164 : Filler List getting compressed in Webkit (Safari) 

---

src/plex-player.js
src/plex.js
web/public/templates/filler-config.html

This fixes playback issues when there's an extra slash in the Plex server uri

Fix #167, extra / in plex uri gives no error during backend route check, but fails when playing the video.

---

dizquetv-nvidia.xml
src/tv-guide-service.js

- nvidia unraid template should use latest-nvidia
- Hopefully improvements to the TV Guide service.

20201030 dev

---

web/directives/channel-config.js
web/directives/filler-config.js
web/public/templates/channel-config.html

Fix all* drag and drop issues in channel and filler lists.
...

Fix all drag and drop issues in channel and filler lists.

---

web/directives/channel-config.js
web/directives/filler-config.js
web/public/templates/channel-config.html

Align 1.1.x fixes into 1.2.x
...

20201120 dev

---

web/directives/channel-config.js
web/public/style.css
web/public/templates/channel-config.html

Add arrows to control channel programming height. Work-around against #182

Add arrows to control channel programming height.

---

src/plexTranscoder.js
src/services/time-slots-service.js
web/directives/channel-config.js
web/directives/time-slots-schedule-editor.js
web/public/index.html
web/public/templates/time-slots-schedule-editor.html

- Align dev/1.1.x into dev/1.2.x
- Time Slots rework.

20201122 dev

---

index.js
package.json
src/xmltv.js

Implement graceful shutdown procedure. So far the only aspect that se…ems to need is is the xmltv writer, we want to make sure the xmltv is completely written before closing the app.  #176

Implement graceful shutdown procedure. 

---

web/directives/channel-config.js

Fix bug with remove duplicates making things break in the channel schedule editor until other tool is used.
...

Fix bug with remove duplicates making things break in the channel schedule editor until other tool is used.

---

README.md
src/constants.js
src/ffmpeg-info.js

* Prepare 1.2.3
* ffmpeg version bug
...

20210109 dev

---

src/ffmpeg.js
web/public/templates/channel-config.html

…
#185 : animated watermark causes stream to lock when switching between videos.

#185 : animated watermark causes stream to lock when switching between videos.

---

src/api.js

#212 add CUID tag to channels in the m3u

#212 add CUID tag to channels in the m3u

---

src/database-migration.js
src/ffmpeg.js
web/directives/ffmpeg-settings.js
web/public/templates/ffmpeg-settings.html

Ability to change the scaling algorithm and default is now bicubic instead of fast_bilinear. Related to #116

Ability to change the scaling algorithm and default is now bicubic instead of fast_bilinear. Related to #116

---

src/plexTranscoder.js

When user define Paths to Direct on Plex Tab Configuration and enable Transcoding on FFMPEG Tab, application never start stream and freeze. 
This return an error because application try to access MediaContainer on getVideoStats and try to make transcoding without codec information.
So what's happening is, when user define Paths to direct, dizquetv only get a file system path (without media codec details), but when define Paths to Plex, dizquetv get a http address with transcoding over Plex (with media codec details).
And when user enable transcoding on FFMPEG tab, dizquetv use information about PATH and Codec Details to generate a ffmpeg streaming.
Now, when user set Transcoding to true and Paths to Direct, dizquetv get codec information and file system path, and only dizquetv make media …

Fixed Direct Play with Transcoding

---

src/ffmpeg.js
src/offline-player.js
src/plex-player.js

Some fixes to ffmpeg stuff.
* Error streams with beep or white noise audio were kind of wrong. I think the tweaks I used the last time to make them less loud actually made them less audible (regardless of volume) , so I restored the old formulae and instead reduce the volume with another filter.
* Fix a typo on logs (streram)
* Fix error stream not being created when offline streams fail.
...

20210117 dev

---

src/api.js
web/directives/channel-config.js
web/public/templates/channel-config.html
web/services/dizquetv.js

Tweaks to image upload . Now supports watermark as well. The api has changed. Dialog browses for Images.

Tweaks to image upload . Now supports watermark as well. The api has changed. Dialog browses for Images.

---

web/directives/channel-config.js

Fix enabling watermark not always loading the defaults

Fix enabling watermark not always loading the defaults.

---

web/directives/channel-config.js

Align 1.2.x into 1.3.x

---

web/directives/channel-config.js
web/public/templates/plex-library.html
web/public/templates/program-config.html
web/services/plex.js

Music Libraries UI
Music libraries seem to be working ok. The only problem so far is that if the image scaling produces odd dimensions it crashes the libx264 encoder. Will have to enforce full resolution normalization or something.

Music Libraries UI

---

src/ffmpeg.js
src/plexTranscoder.js

Tweaks and fixes to music player.

Tweaks and fixes to music player.

---

src/helperFuncs.js
web/directives/channel-config.js

20210215 dev

---

README.md
src/constants.js
src/xmltv.js

Prepare 1.2.5 development
Fix xmltv in tivimate
...

20210228 dev

---

web/controllers/guide.js
web/directives/channel-config.js
web/public/index.html
web/public/templates/channel-config.html

* Wider UI
* TV Guide starting zoom setting
* Fix a typo in tool help
* Discord invite to rules channel.
* Removing duplicates before running time slots.
...

20210315 dev

---

web/public/templates/channel-config.html

#287 Increase max filler cooldowns to 7 day

---

src/video.js
web/app.js
web/controllers/player.js
web/public/index.html
web/public/templates/channel-config.html
web/public/templates/plex-library.html
web/public/views/player.html

* Player
* Max filler cooldown is 7 days
* Small visual improvement to library import dialog.

20210323 dev

---

README.md
src/constants.js
src/dao/custom-show-db.js
src/dao/plex-server-db.js
web/controllers/custom-shows.js
web/services/plex.js

20210516 dev

---

package.json
src/api.js
src/plexTranscoder.js
src/tv-guide-service.js
web/controllers/channels.js
web/services/dizquetv.js

* Fix playback issues introduced when adding music library support (hopefully)
* TV Guide updates much quicker than before.
* Opening a big channel in the UI will not cause a short playback freeze.

20210530 dev

---

package-lock.json
package.json
pull_request_template.md
web/public/templates/channel-config.html

20210531 dev

---

web/services/plex.js

#308 Fix shows appearing only in two collections

---

src/helperFuncs.js
src/video.js

Fix #330, programs cut off the last few milliseconds of a program, up to 30 seconds

Fix #330, programs cut off the last few milliseconds of a program, up to 30 seconds

---

README.md
src/constants.js

Prepare 1.4.4 development

---

.husky/commit-msg
.husky/prepare-commit-msg
README.md
commitlint.config.js
package-lock.json
package.json

Implementation of https://www.conventionalcommits.org/, a pattern to commit's message with a focus on automation and human read.
With conventional commits, we can semi-automate (@vexorian using cli) or full-automate (using github-actions after @vexorian approves) releases using https://github.com/semantic-release/semantic-release.
All release information are build using commits information. Description, version number based on Semantic Versioning, links. 
Look the example:
These changes don't affect the application development, build or run.
- `Commitlint` is added to validate all new commits and help developers remember to use patter, before to send to remote repository.
- `cz-cli` aka `Commitizen` makes available a cli utility to help developer to create commits.
- `Husky` are add for …

Conventional Commits

---

src/api.js
src/database-migration.js
src/services/random-slots-service.js

Align dev/1.4.x into dev/1.5.x
...

20210808 dev

---

src/helperFuncs.js
src/video.js

Do not clone whole channel just to combine the channel

Do not clone whole channel just to combine the channel

---

index.js
src/api.js
src/channel-cache.js
src/constants.js
src/dao/filler-db.js
src/dao/plex-server-db.js
src/helperFuncs.js
src/services/active-channel-service.js
src/services/channel-service.js
src/services/m3u-service.js
src/services/on-demand-service.js
src/services/tv-guide-service.js
src/video.js
web/directives/channel-config.js

* Align with 1.4.x
* Fix rewind/fast forward tool bug introduced with on-demand channels.
* Channel Service refactor. Now there is a Channel Service and it handles multiple things that used to require 
* Updating a channel that's currently playing will also update the stream
* X ] Backwards compatibility: Users running the new code using an existing .disquetv folder will not lose their channels / settings.

20210809 dev

---

src/services/channel-service.js
src/video.js

Fix playback issues after the latest commit. Specially the fiurst video not playing in an on-demand channel

Fix playback issues after the latest commit. Specially the fiurst video not playing in an on-demand channel

---

src/helperFuncs.js
src/services/m3u-service.js

* m3u sorting
* Fille Randoms algorithm

20210912 dev

---

web/directives/plex-library.js
web/services/plex.js

#365 Fix Libraries with many elements in multiple collections taking too long to load.
...

#365 Fix Libraries with many elements in multiple collections taking too long to load.

---

src/helperFuncs.js

Remove some unnecessary logs

---

src/channel-cache.js
src/video.js
web/services/plex.js

* Fix #369 
* Add Smart collection support.

20210919 dev

---

Dockerfile-nvidia
README.md
index.js
src/api.js
src/constants.js
web/controllers/version.js
web/directives/channel-config.js
web/public/views/version.html

* Fix nvidia docker builds.
* Fix channels with numbers smaller than 10 not being allowed by the UI.
* Added checks for nodejs version and entry in the version page.

20210920 dev

---

.github/workflows/development-tag.yaml
.github/workflows/docker-build.yaml
.github/workflows/edge-tag.yaml
.github/workflows/latest-tag.yaml
.github/workflows/named-tag.yaml

Github actions to build and push docker images.

---

.github/workflows/binaries-build.yaml
.github/workflows/development-binaries.yaml
.github/workflows/tag-binaries.yaml

Automatically build and upload binary files for releases and development branch..

Automatically build and upload binary files for releases and development branch..
